=pod

=head1 POD-mode: Emacs Plain Old Documentation format major mode

=for html <img src="mascot.jpg" alt="pod-mode mascot">

=head2 Thoughts

There's a good way to do this (parsing the podfile and operating on lisp lists), which isn't the way I'm going to do it. 
Instead, I shall be using the time-tested technique of blind macros and the less-tested technique of L<structural regex|https://doc.cat-v.org/bell_labs/structural_regexps/>.

=head2 DONE

=over

=item Function for inserting boilerplate in empty file

=item Insert heading (1/2/3/4/5/6)

=item Insert list indent

=item Insert list item

=item Begin/end block

=item For block

=item Marking up region (italic/bold/hyperlink/code/escape/filename/nbsp text/Z<>)

=item Spawning markup

=item Keymap for above functions

=item Rendering and showing in EWW

=item Hook for inserting boilerplate in empty file

=back

=head2 TODO

Boilerplate runs on hook, so no problem there

Structural = M, markup = C (that way I can reuse mnemonic binds)

Headings: C-c M-1/2/3/4/5/6

List: C-c M-l (list)

Item: C-c M-i (item)

Begin/end: C-c M-b (block)

For: C-c M-f

Italic: C-c C-S-i (italicize region), C-c C-i (insert italics)

Bold: C-c C-S-b (bold region), C-c C-b (insert bold)

Link: C-c C-S-l (link region), C-c C-l (insert link)

Code: C-c C-S-c (code region), C-c C-c (insert code)

Escape: C-c C-e

Filename: C-c C-f

Nonbreaking space text: C-c C-S-s (region), C-c C-s (insert)

ZZ<><Z<>>: C-c C-z

Render: C-c C-r

Render and display as HTML: C-c M-r

=head2 Resources

L<Keymapping|http://xahlee.info/emacs/emacs/elisp_create_major_mode_keymap.html>

L<POD overview|https://perldoc.perl.org/perlpod>

=cut
